In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [48]:
input_layer = np.array([[0,0,1] , [1,1,1] ,[1,0,1] ,[0,1,1] , [0,0,0] , [1,1,0]])
output_layer = np.array([[0,1,0,0,0,0]]).T

In [49]:
input_layer.shape

(6, 3)

In [50]:
output_layer.shape

(6, 1)

In [51]:
np.random.seed(1)
weight = 2 * np.random.random((3,1)) -1
b = 0

for iteration in range(7000):
    predicted_output_layer = sigmoid(np.dot(input_layer , weight) + b )
    weight = weight - np.dot(input_layer.T , predicted_output_layer - output_layer)
    b= b - np.sum(predicted_output_layer - output_layer)

print(predicted_output_layer.ravel() , b )
print(weight.ravel())

[2.33234495e-09 9.97702132e-01 1.00530408e-03 1.00530408e-03
 5.40570968e-15 1.00530735e-03] -32.852038702097566
[12.97521951 12.97521951 12.97521625]


In [52]:
sigmoid(np.dot(np.array([[1,1,0]]) , weight) + b )

array([[0.00100516]])

In [6]:
np.random.seed(1)
weight = 2 * np.random.random((3,1)) -1
b = 100

for iteration in range(700):
    predicted_output_layer = sigmoid(np.dot(input_layer , weight) + b )
    weight = weight - np.dot(input_layer.T , predicted_output_layer - output_layer)
    b= b - np.sum(predicted_output_layer - output_layer)

print(predicted_output_layer.ravel() , b )
print(weight.ravel())

[4.15457637e-13 9.98909773e-01 1.89487948e-05 2.00880340e-05
 2.67129305e-03] -5.924137869907578
[ 17.63671574  17.69509973 -22.58582678]


In [7]:
np.random.seed(1)
weight = np.array([[100],[100],[100]])
b = -90

for iteration in range(700):
    predicted_output_layer = sigmoid(np.dot(input_layer , weight) + b )
    weight = weight - np.dot(input_layer.T , predicted_output_layer - output_layer)
    b= b - np.sum(predicted_output_layer - output_layer)

print(predicted_output_layer.ravel() , b )
print(weight.ravel())

[8.57133328e-38 1.00000000e+00 2.93383674e-04 2.93383674e-04
 1.61639839e-60] -137.67549188648593
[77.21578094 77.21578094 52.32450811]


In [8]:
np.random.seed(1)
weight = np.array([[100],[100],[100]])
b = 90

for iteration in range(700):
    predicted_output_layer = sigmoid(np.dot(input_layer , weight) + b )
    weight = weight - np.dot(input_layer.T , predicted_output_layer - output_layer)
    b= b - np.sum(predicted_output_layer - output_layer)

print(predicted_output_layer.ravel() , b )
print(weight.ravel())

[1.08422602e-28 1.00000000e+00 3.02760611e-04 3.02760611e-04
 7.04333227e-22] -48.70539617511979
[ 56.28894814  56.28894814 -15.68733108]


In [9]:
from sklearn.datasets import load_digits , make_blobs
digits = load_digits()


In [10]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [11]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [12]:
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
digits.data[0].

SyntaxError: invalid syntax (<ipython-input-13-9ad215d47a02>, line 1)

In [ ]:
df = pd.DataFrame(digits.data)
df.head()

In [ ]:
df["target"] = digits.target
df.target.value_counts()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(df.drop("target",axis=1), df.target , test_size=0.3 , stratify=df.target ) 

In [ ]:
y_train.value_counts()

In [ ]:
y_train_df = pd.DataFrame(y_train)
y_train_df.head()

In [ ]:
op_layer = pd.get_dummies(y_train_df.target).T
op_layer

In [ ]:
input_layer = x_train
output_layer = op_layer

np.random.seed(1)
weight = 2 * np.random.random((64,1)) -1
b = 90

for iteration in range(1):
    predicted_output_layer = sigmoid(np.dot(input_layer , weight) + b )
    weight = weight - np.dot(input_layer.T , predicted_output_layer - output_layer)
    b= b - np.sum(predicted_output_layer - output_layer)

print(predicted_output_layer.ravel() , b )
print(weight.ravel())

In [ ]:
input_layer.shape , weight.shape